// =============================================================================
// DADOS DAS BASES — edite aqui e rode: node upload-cards.js
// =============================================================================
module.exports = [
  {
    title: "BASE DE CASCAVEL",
    finished: false,
    mac: "b8:27:eb:a9:a9:3b",
    code: "CA01",
    link: "http://45.161.184.183:10005/logs",
    municipality: "Cascavel",
    state: "CE",
    location: "Sede Topodatum",
    receiver: "u-blox F9P",
    antenna: "BEIBT800D NONE",
    antennaHeight: "8.65m",
    installDate: "Mar/2022",
    access: "Sede da empresa Topodatum, acesso pela rodovia CE-060, zona urbana de Cascavel-CE.",
    responsible: "Topodatum Topografia",
    coordinates: [
      { radius: "CA01", east: "000000.000", sigmaX: "0.000", north: "0000000.000", sigmaY: "0.000", height: "000.00", SigmaZ: "0.000", location: "Sede Topodatum", antennaHeight: "8.65m" },
    ],
  },
  {
    title: "BASE DE MISSÃO VELHA",
    finished: false,
    mac: "b8:27:eb:79:4d:87",
    code: "MV01",
    link: "http://45.161.184.183:10002/status",
    municipality: "Missão Velha",
    state: "CE",
    location: "Centro",
    receiver: "u-blox F9P",
    antenna: "BEIBT800D NONE",
    antennaHeight: "1.75m",
    installDate: "Jan/2022",
    access: "Zona urbana de Missão Velha-CE, acesso pelo centro da cidade.",
    responsible: "Topodatum Topografia",
    coordinates: [
      { radius: "MV01", east: "000000.000", sigmaX: "0.000", north: "0000000.000", sigmaY: "0.000", height: "000.00", SigmaZ: "0.000", location: "Centro", antennaHeight: "1.75m" },
    ],
  },
  {
    title: "BASE DE PORTEIRAS",
    finished: false,
    mac: "b8:27:eb:04:a0:bf",
    code: "PO01",
    link: "http://45.161.184.183:10004/status",
    municipality: "Porteiras",
    state: "CE",
    location: "Centro",
    receiver: "u-blox F9P",
    antenna: "BEIBT800D NONE",
    antennaHeight: "1.75m",
    installDate: "Fev/2022",
    access: "Zona urbana de Porteiras-CE, acesso pelo centro da cidade.",
    responsible: "Topodatum Topografia",
    coordinates: [
      { radius: "PO01", east: "000000.000", sigmaX: "0.000", north: "0000000.000", sigmaY: "0.000", height: "000.00", SigmaZ: "0.000", location: "Centro", antennaHeight: "1.75m" },
    ],
  },
  {
    title: "BASE DE JUAZEIRO DO NORTE",
    finished: true,
    mac: "",
    code: "JN01",
    link: "http://45.161.184.183:10006/status",
    finishedDate: "—",
    municipality: "Juazeiro do Norte",
    state: "CE",
    location: "Parque de Vaquejada",
    receiver: "u-blox F9P",
    antenna: "BEIBT800D NONE",
    antennaHeight: "1.75m",
    installDate: "Abr/2022",
    access: "Parque de Vaquejada, Juazeiro do Norte-CE, acesso pela Avenida Padre Cícero.",
    responsible: "Topodatum Topografia",
    coordinates: [
      { radius: "JN01", east: "000000.000", sigmaX: "0.000", north: "0000000.000", sigmaY: "0.000", height: "000.00", SigmaZ: "0.000", location: "Parque de Vaquejada", antennaHeight: "1.75m" },
    ],
  },
  {
    title: "BASE DE ARARIPE",
    finished: true,
    mac: "",
    code: "AR01",
    link: "http://45.161.184.183:10007/status",
    finishedDate: "—",
    municipality: "Araripe",
    state: "CE",
    location: "Centro",
    receiver: "u-blox F9P",
    antenna: "BEIBT800D NONE",
    antennaHeight: "1.75m",
    installDate: "Mai/2022",
    access: "Zona urbana de Araripe-CE, acesso pelo centro da cidade.",
    responsible: "Topodatum Topografia",
    coordinates: [
      { radius: "AR01", east: "000000.000", sigmaX: "0.000", north: "0000000.000", sigmaY: "0.000", height: "000.00", SigmaZ: "0.000", location: "Centro", antennaHeight: "1.75m" },
    ],
  },
  {
    title: "BASE DE CATARINA",
    finished: false,
    mac: "b8:27:eb:d2:62:b0",
    code: "CT01",
    link: "http://45.161.184.183:10008/logs",
    municipality: "Catarina",
    state: "CE",
    location: "Centro",
    receiver: "u-blox F9P",
    antenna: "BEIBT800D NONE",
    antennaHeight: "1.75m",
    installDate: "Jun/2022",
    access: "Zona urbana de Catarina-CE, acesso pelo centro da cidade.",
    responsible: "Topodatum Topografia",
    coordinates: [
      { radius: "CT01", east: "000000.000", sigmaX: "0.000", north: "0000000.000", sigmaY: "0.000", height: "000.00", SigmaZ: "0.000", location: "Centro", antennaHeight: "1.75m" },
    ],
  },
  {
    title: "BASE DE QUIXERAMOBIM",
    finished: false,
    mac: "b8:27:eb:b0:16:3f",
    code: "QX01",
    link: "",
    municipality: "Quixeramobim",
    state: "CE",
    location: "Centro",
    receiver: "u-blox F9P",
    antenna: "BEIBT800D NONE",
    antennaHeight: "1.75m",
    installDate: "",
    access: "",
    responsible: "Topodatum Topografia",
    coordinates: [
      { radius: "QX01", east: "000000.000", sigmaX: "0.000", north: "0000000.000", sigmaY: "0.000", height: "000.00", SigmaZ: "0.000", location: "Centro", antennaHeight: "1.75m" },
    ],
  },
    {
    title: "BASE DE NENELANDIA 02",
    finished: true,
    mac: "",
    code: "QX02",
    link: "",
    finishedDate: "Abr/2026",
    municipality: "Quixeramobim",
    state: "CE",
    location: "Nenelândia",
    receiver: "u-blox F9P",
    antenna: "NÃO DISPONÍVEL",
    antennaHeight: "1.75m",
    installDate: "Abr/2026",
    access: "Localidade de Nenelândia, zona rural de Quixeramobim-CE.",
    responsible: "Topodatum Topografia",
    coordinates: [
      {
        radius: "QX02",
        east: "477776.946",
        sigmaX: "0.001",
        north: "9397990.562",
        sigmaY: "0.000",
        height: "194.46",
        SigmaZ: "0.002",
        location: "Nenelândia",
        antennaHeight: "1.75m"
      }
    ],
  },
  {
    title: "BASE DE MARANGUAPE",
    finished: false,
    mac: "b8:27:eb:6f:a5:02",
    code: "MR01",
    link: "",
    municipality: "Maranguape",
    state: "CE",
    location: "Centro",
    receiver: "u-blox F9P",
    antenna: "BEIBT800D NONE",
    antennaHeight: "1.75m",
    installDate: "",
    access: "",
    responsible: "Topodatum Topografia",
    coordinates: [
      { radius: "MR01", east: "000000.000", sigmaX: "0.000", north: "0000000.000", sigmaY: "0.000", height: "000.00", SigmaZ: "0.000", location: "Centro", antennaHeight: "1.75m" },
    ],
  },

  {
    title: "BASE DE CRUZ",
    finished: false,
    mac: "b8:27:eb:a9:a9:3b",
    code: "MC01",
    link: "",
    municipality: "Marco",
    state: "CE",
    location: "Sede Topodatum",
    receiver: "u-blox F9P",
    antenna: "BEIBT800D NONE",
    antennaHeight: "8.65m",
    installDate: "Mar/2022",
    access: "Sede da empresa Topodatum, acesso pela rodovia CE-179, zona urbana de Marco-CE.",
    responsible: "Topodatum Topografia",
    coordinates: [
      { radius: "MC01", east: "000000.000", sigmaX: "0.000", north: "0000000.000", sigmaY: "0.000", height: "000.00", SigmaZ: "0.000", location: "Sede Topodatum", antennaHeight: "8.65m" },
    ],
  },

];
